name: Publish Rust
description: Build and publish rust packages to crates-io
author: FL03

# Define your inputs here.
inputs:
  all-features:
    default: true
    description: build and publish all availible features
    required: true
  package:
    description: The name of the package being published
    required: true
  platform:
    default: ubuntu-latest
    description: The operating system of the runner
    required: true
  target:
    default: x86_64-unknown-linux-gnu
    description: The target to build the crate with
    required: true
  toolchain:
    default: stable
    description: The rustup toolchain to leverage when building the crate
    required: true
  who-to-greet:
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
